### ISSUE TITLE
530le等混动车的适配问题

### ISSUE THREAD

**Issue by burdening3** [opp100/bmw-scriptable-widgets#1]
混动车的data.status.fuelIndicators数据格式和油车不一样
levelValue数据显示异常
![微信图片_20211103112446](https://user-images.githubusercontent.com/33069586/140006113-a388d517-d62a-4ed9-8ca1-c20367023f20.jpg)

修改后的效果
![微信图片_20211103112801](https://user-images.githubusercontent.com/33069586/140006211-f4eb8655-8114-4bf4-a3ff-86392d3bb19f.jpg)

以我自己的车为例，该变量是一个长度为3的数组，且data.status.fuelIndicators[0]不包含levelValue, levelUnits
  fuelIndicators: [
    {
      infoLabel: '组合续航里程',
      levelValue: null,
      isInaccurate: false,
      infoIconId: 59691,
      rangeUnits: 'km',
      levelUnits: null,
      rangeIconId: 59691,
      iconOpacity: 'high',
      showsBar: false,
      rangeValue: '38
      levelIconId: null,
      secondaryBarValue: 0,
      mainBarValue: 0,
      isCircleIcon: false,
      chargingType: null
    },
    {
      infoLabel: '100% 约凌晨03:12',
      showBarGoal: false,
      rangeValue: '34',
      levelValue: '76',
      infoIconId: 59689,
      rangeUnits: 'km',
      levelUnits: '%',
      rangeIconId: 59683,
      isInaccurate: true,
      showsBar: true,
      iconOpacity: 'high',
      levelIconId: 59689,
      secondaryBarValue: 0,
      chargingStatusType: 'CHARGING',
      mainBarValue: 76,
      barType: null,
      isCircleIcon: true,
      chargingType: 'charging',
      chargingStatusIndicatorType: 'CHARGING'
    },
    {
      infoLabel: '油位',
      rangeValue: '351',
      levelValue: '31',
      infoIconId: 59930,
      rangeUnits: 'km',
      levelUnits: 'l',
      rangeIconId: 59681,
      iconOpacity: 'high',
      showsBar: false,
      isInaccurate: true,
      levelIconId: 59682,
      secondaryBarValue: 0,
      mainBarValue: 0,
      isCircleIcon: false,
      chargingType: null
    }
  ],

所以我把那一行改成了
            const {rangeValue, rangeUnits} = data.status.fuelIndicators[0];
            const {levelValue, levelUnits} = data.status.fuelIndicators[1];
levelValue代表了电池电量

我觉得可以针对混动车型做一个适配

**Comment by opp100** [comment]
感谢反馈，我之后会把混动车型适配加进去

**Comment by opp100** [comment]
已经添加了支持，文字应该能正确显示了

**Comment by opp100** [comment]
能不能麻烦在My bmw里面截个图，方便更新UI

**Comment by burdening3** [comment]
![d92298593ff7b008c1c4e3eeb233928](https://user-images.githubusercontent.com/33069586/140164458-ab440da7-e33b-4bfe-8bdd-3cf42b68ab17.jpg)
具体需要什么图呢？

**Comment by opp100** [comment]
谢谢，主要是想看看这个MY BMW是怎么怎么给混动车布局油耗、里程数之类的信息的。
