### ISSUE TITLE
填入高德API_KEY之后，地图显示黑掉一部分

### ISSUE THREAD

**Issue by Primovist** [opp100/bmw-scriptable-widgets#17]
今早更新之后，小组件更新信息后是正常的，过几分钟之后再看地图黑了一边。
![30851529-2FCD-40CD-9230-9874BA32353F](https://user-images.githubusercontent.com/2242315/164408093-acb58b49-b23e-4eb2-b8cc-4e04ca5fcff3.png)

**Comment by primovist** [comment]
![正在上传 164407947...]

**Comment by Primovist** [comment]
本来以为自己修复了，今天发现是不更新了😂更新之后还是黑一半。
