### ISSUE TITLE
428早上又不能登陆了

### ISSUE THREAD

**Issue by cw0423** [opp100/bmw-scriptable-widgets#18]
428早上又不能登陆了
提示登陆失败

**Comment by PhantomThief** [comment]
+1

**Comment by Chao-Zeng** [comment]
怎么回事，是宝马官方出了小组件后在排斥这个小组件么？

**Comment by jackiehj** [comment]
+1

**Comment by j0uz** [comment]
- 重新登录提示系统版本有更新
- 签到功能报异常：no auth

**Comment by Yixi** [comment]
应该又需要更新下user agent 里面模拟的客户端版本号了。。

**Comment by Primovist** [comment]
抓个版本号填进去应该就可以了。

**Comment by Primovist** [comment]
My%20BMW/13603 CFNetwork/1331.0.7 Darwin/21.4.0
这个该咋搞进去？

**Comment by AllenAlex-1014** [comment]
我看了一下。my bmw的版本号没变。 应该是其他地方有调整。 暂时没找到位置

**Comment by AllenAlex-1014** [comment]
> 我看了一下。my bmw的版本号没变。 应该是其他地方有调整。 暂时没找到位置

报错提示：{"code":499100,"data":null,"msgType":"toast","error":true,"description":"请前往应用市场获取最新版本"}

**Comment by sayayuka** [comment]
> > 我看了一下。my bmw的版本号没变。 应该是其他地方有调整。 暂时没找到位置
> 
> 报错提示：{"code":499100,"data":null,"msgType":"toast","error":true,"description":"请前往应用市场获取最新版本"}

+1，同样的错

**Comment by Primovist** [comment]
但是我觉得应该还是Header的问题。

**Comment by iakoug** [comment]
看起来不太稳定的样子，最近两个月出现几次

**Comment by lvjisong** [comment]
同样的问题

**Comment by justethan** [comment]
降级版本好像好了 我bmw降级到2.1了

**Comment by ksong008** [comment]
> 降级版本好像好了 我bmw降级到2.1了

怎么降级的

**Comment by vinsonma** [comment]
> > > 我看了一下。my bmw的版本号没变。 应该是其他地方有调整。 暂时没找到位置
> > 
> > 
> > 报错提示：{"code":499100,"data":null,"msgType":"toast","error":true,"description":"请前往应用市场获取最新版本"}
> 
> +1，同样的错



> > > 我看了一下。my bmw的版本号没变。 应该是其他地方有调整。 暂时没找到位置
> > 
> > 
> > 报错提示：{"code":499100,"data":null,"msgType":"toast","error":true,"description":"请前往应用市场获取最新版本"}
> 
> +1，同样的错

+1 ，同样的错

**Comment by vinsonma** [comment]
> > > 我看了一下。my bmw的版本号没变。 应该是其他地方有调整。 暂时没找到位置
> > 
> > 
> > 报错提示：{"code":499100,"data":null,"msgType":"toast","error":true,"description":"请前往应用市场获取最新版本"}
> 
> +1，同样的错

+1，同样的错，重试多次。

**Comment by Primovist** [comment]
昨天试了一下安卓的那个第三方app，密码登录不可以，但是提示用验证码登陆，后来验证码成功了。不知道脚本可以不可以。

**Comment by opp100** [comment]
已更新，scriptable里面检查更新并重新登陆
