### ISSUE TITLE
4.29 签到提示no auth，签到失败

### ISSUE THREAD

**Issue by hellopony** [opp100/bmw-scriptable-widgets#19]
签到失败后会一直不停尝试，不断有no auth 跳出来，直到退出登录，可能是认证方式在服务器后台变化了，我这边直到昨天都是好的

**Comment by TreeLiked** [comment]
+1，退出登录后登录不了了😂

**Comment by jyan1011** [comment]
+1,两天了

**Comment by BesenZhang** [comment]
现在一直get token error

**Comment by TioMiss** [comment]
是不是官方开始封第三方组件了😓

**Comment by vinsonma** [comment]
报错提示：{"code":499100,"data":null,"msgType":"toast","error":true,"description":"请前往应用市场获取最新版本"}

**Comment by jeffreylyg** [comment]
有解决方案了吗？

**Comment by opp100** [comment]
已更新，scriptable里面检查更新并重新登陆
