### ISSUE TITLE
多个车辆改车架号还显示为默认车辆

### ISSUE THREAD

**Issue by umxyz** [opp100/bmw-scriptable-widgets#2]

**Comment by umxyz** [comment]
输入车架号后加密的字符串一样
![image](https://user-images.githubusercontent.com/44895726/140010331-8edf7182-5621-4253-9e1c-95f33631ccba.png)

**Comment by opp100** [comment]
感谢反馈，确实图片的MD5有一点问题，我在改改

**Comment by opp100** [comment]
已修复
