### ISSUE TITLE
安装了另外一位大神的组件后，这个组件神奇的好了

### ISSUE THREAD

**Issue by Joey0217** [opp100/bmw-scriptable-widgets#21]
![IMG_0746](https://user-images.githubusercontent.com/36755962/167247630-8cf370f9-e7c6-4e35-93cb-cc403bad638b.JPG)

**Comment by jyan1011** [comment]
请问是什么组件？

**Comment by Joey0217** [comment]
https://huchundong.gitee.io/qjl-rapv06-ffj/

**Comment by cold-l** [comment]
![image](https://user-images.githubusercontent.com/46069621/167250980-c7a9b965-4a7f-41da-8ff2-7c0bc27f5558.jpeg)

看着就比较像，大概看了下，登陆方式有点区别，不知道作者是不是太忙了，没空搞这个

**Comment by lvjisong** [comment]
我也安装了另一个，不过这个还是登录不上

**Comment by opp100** [comment]
已更新，scriptable里面检查更新试试
