### ISSUE TITLE
关于用户密码RSA加密实现的建议

### ISSUE THREAD

**Issue by lishuzhi1121** [opp100/bmw-scriptable-widgets#3]
建议脚本中将用户密码进行rsa加密的时候不要使用第三方接口进行加密，这样会导致用户密码直接明文暴露在网络传输里，可以改为直接使用js代码实现的rsa加密方式进行本地加密，既能提高效率，又能保护用户隐私，参考：https://github.com/travist/jsencrypt ，小小建议～

![](https://raw.githubusercontent.com/lishuzhi1121/oss/master/uPic/2021/11/03-160216-iShot2021-11-03%2015.56.01.png)

**Comment by opp100** [comment]
谢谢建议，这个jsencrypt没有办法直接引用，并且它依赖于有些node原生的组件。
可能需要重写，工程量可能比较大。我到时候慢慢的加入。

**Comment by opp100** [comment]
已经本地化
