### ISSUE TITLE
请问我想把总里程修改成上次充电后的里程应该如何操作

### ISSUE THREAD

**Issue by panyao33** [opp100/bmw-scriptable-widgets#5]
目前显示的总里程我想修改代码换成上次充电后里程，不过不知道这个属性叫什么请问作者大神知道吗？ 大概意思就是Mileage after last charger。在新的my bmw里也看不到，老的互联驾驶app里有，估计是隐藏了如果知道API里定义也许可以调出来。

**Comment by lishuzhi1121** [comment]
> 目前显示的总里程我想修改代码换成上次充电后里程，不过不知道这个属性叫什么请问作者大神知道吗？ 大概意思就是Mileage after last charger。在新的my bmw里也看不到，老的互联驾驶app里有，估计是隐藏了如果知道API里定义也许可以调出来。

你可以用自己的账号调用一下My BMW的官方接口，看一下返回的数据里有没有大概符合你自己的车子上次充电后的里程数字的字段，如果有的话就比较好修改了。

**Comment by opp100** [comment]
> 目前显示的总里程我想修改代码换成上次充电后里程，不过不知道这个属性叫什么请问作者大神知道吗？ 大概意思就是Mileage after last charger。在新的my bmw里也看不到，老的互联驾驶app里有，估计是隐藏了如果知道API里定义也许可以调出来。

这个你可以试着把`/eadrax-vcs/v1/vehicles`的response 用console.log出来看看，应该在`status.fuelIndicators`下面有写

**Comment by panyao33** [comment]
> > 目前显示的总里程我想修改代码换成上次充电后里程，不过不知道这个属性叫什么请问作者大神知道吗？ 大概意思就是Mileage after last charger。在新的my bmw里也看不到，老的互联驾驶app里有，估计是隐藏了如果知道API里定义也许可以调出来。
> 
> 你可以用自己的账号调用一下My BMW的官方接口，看一下返回的数据里有没有大概符合你自己的车子上次充电后的里程数字的字段，如果有的话就比较好修改了。

谢谢，我试试看

**Comment by panyao33** [comment]
> > 目前显示的总里程我想修改代码换成上次充电后里程，不过不知道这个属性叫什么请问作者大神知道吗？ 大概意思就是Mileage after last charger。在新的my bmw里也看不到，老的互联驾驶app里有，估计是隐藏了如果知道API里定义也许可以调出来。
> 
> 这个你可以试着把`/eadrax-vcs/v1/vehicles`的response 用console.log出来看看，应该在`status.fuelIndicators`下面有写

好的，我看看，感谢！
