### ISSUE TITLE
希望有530Li系列车型的图片

### ISSUE THREAD

**Issue by multics** [opp100/bmw-scriptable-widgets#6]

**Comment by multics** [comment]
或者有个黑色530Li的图片URL也行，我给配上也能用。现在显示灰色罩子蒙着车辆。

**Comment by opp100** [comment]
> 或者有个黑色530Li的图片URL也行，我给配上也能用。现在显示灰色罩子蒙着车辆。

自定义车辆URL那里什么都不填写就是自动从MY BMW获取了。
